import { Productos } from '@/interfaces/interfaces';

export const seed_productos: Productos[] = [
  {
    id: 'p1',
    id_categoria: 1,
    oferta: true,
    compra: true,
    like: true,
    _count: { likes: 120, ventas: 35 },
    likeCount: 120,
    nombre: 'Editor de Código Pro',
    descripcion:
      'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.',
    precio: 49.99,
    precio_actual: { precio: 39.99, descuento: 20 },
    fecha_registro: new Date('2024-07-15'),
    requisitos_tecnicos: 'Windows 10, 4GB RAM, 500MB disco',
    categorias: {
      id: 'c1',
      nombre: 'Desarrollo',
      _count: { productos: '3', usuarios: '0', productos_ofertas: '2' },
      productos: [],
    },
    plan: {
      id: 'pl1',
      nombre: 'Plan Pro',
      costo: 9.99,
      beneficios: 'Acceso a actualizaciones y soporte premium',
      _count: { suscripciones: 100, productos: 2 },
      suscripciones: [],
      productos: [],
      gananciasMensuales: 999,
    },
    versiones: [
      {
        id: 'v1',
        producto_id: 'p1',
        numero_version: '1.0.0',
        urlarchivo: 'https://example.com/editor-v1.zip',
        fecha_lanzamiento: new Date('2025-09-17'),
        descripcion_cambios: 'Versión inicial',
        size: '50MB',
        productos: {} as Productos,
      },
    ],
    registro_productos: [],
    productos_ofertas: [],
  },
  {
    id: 'p2',
    id_categoria: 2,
    oferta: false,
    compra: true,
    like: false,
    _count: { likes: 50, ventas: 20 },
    likeCount: 50,
    nombre: 'Antivirus Shield',
    descripcion:
      'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.',
    precio: 29.99,
    precio_actual: { precio: 29.99, descuento: 0 },
    fecha_registro: new Date('2024-08-01'),
    requisitos_tecnicos: 'Windows 7+, 2GB RAM, 200MB disco',
    categorias: {
      id: 'c2',
      nombre: 'Seguridad',
      _count: { productos: '2', usuarios: '0', productos_ofertas: '1' },
      productos: [],
    },
    plan: {
      id: 'pl2',
      nombre: 'Plan Básico',
      costo: 4.99,
      beneficios: 'Protección básica y actualizaciones automáticas',
      _count: { suscripciones: 50, productos: 1 },
      suscripciones: [],
      productos: [],
      gananciasMensuales: 249,
    },
    versiones: [
      {
        id: 'v2',
        producto_id: 'p2',
        numero_version: '2.1.0',
        urlarchivo: 'https://example.com/antivirus-v2.zip',
        fecha_lanzamiento: new Date('2024-08-05'),
        descripcion_cambios: 'Mejora en el motor de detección',
        size: '100MB',
        productos: {} as Productos,
      },
    ],
    registro_productos: [],
    productos_ofertas: [],
  },
  {
    id: 'p3',
    id_categoria: 3,
    oferta: true,
    compra: true,
    like: true,
    _count: { likes: 200, ventas: 60 },
    likeCount: 200,
    nombre: 'Suite de Ofimática Plus',
    descripcion:
      'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.',
    precio: 79.99,
    precio_actual: { precio: 59.99, descuento: 25 },
    fecha_registro: new Date('2024-06-10'),
    requisitos_tecnicos: 'Windows/Mac, 8GB RAM',
    categorias: {
      id: 'c3',
      nombre: 'Productividad',
      _count: { productos: '2', usuarios: '0', productos_ofertas: '1' },
      productos: [],
    },
    plan: {
      id: 'pl3',
      nombre: 'Plan Empresarial',
      costo: 19.99,
      beneficios: 'Soporte corporativo y licencias múltiples',
      _count: { suscripciones: 200, productos: 1 },
      suscripciones: [],
      productos: [],
      gananciasMensuales: 3999,
    },
    versiones: [
      {
        id: 'v3',
        producto_id: 'p3',
        numero_version: '3.2.0',
        urlarchivo: 'https://example.com/ofimatica-v3.zip',
        fecha_lanzamiento: new Date('2024-07-01'),
        descripcion_cambios: 'Compatibilidad con nuevos formatos',
        size: '250MB',
        productos: {} as Productos,
      },
    ],
    registro_productos: [],
    productos_ofertas: [],
  },
  {
    id: 'p4',
    id_categoria: 1,
    oferta: false,
    compra: true,
    like: false,
    _count: { likes: 80, ventas: 15 },
    likeCount: 80,
    nombre: 'IDE Mobile Studio',
    descripcion:
      'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.',
    precio: 99.99,
    precio_actual: { precio: 99.99, descuento: 0 },
    fecha_registro: new Date('2024-04-22'),
    requisitos_tecnicos: 'Windows/Mac/Linux, 16GB RAM',
    categorias: {
      id: 'c1',
      nombre: 'Desarrollo',
      _count: { productos: '3', usuarios: '0', productos_ofertas: '2' },
      productos: [],
    },
    plan: {
      id: 'pl1',
      nombre: 'Plan Pro',
      costo: 9.99,
      beneficios: 'Acceso a actualizaciones y soporte premium',
      _count: { suscripciones: 100, productos: 2 },
      suscripciones: [],
      productos: [],
      gananciasMensuales: 999,
    },
    versiones: [
      {
        id: 'v4',
        producto_id: 'p4',
        numero_version: '1.5.0',
        urlarchivo: 'https://example.com/mobile-ide-v1.5.zip',
        fecha_lanzamiento: new Date('2024-05-10'),
        descripcion_cambios: 'Compatibilidad con Flutter',
        size: '300MB',
        productos: {} as Productos,
      },
    ],
    registro_productos: [],
    productos_ofertas: [],
  },
  {
    id: 'p5',
    id_categoria: 4,
    oferta: true,
    compra: true,
    like: true,
    _count: { likes: 400, ventas: 150 },
    likeCount: 400,
    nombre: 'PhotoMaster Studio',
    descripcion:
      'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.',
    precio: 59.99,
    precio_actual: { precio: 44.99, descuento: 25 },
    fecha_registro: new Date('2024-02-10'),
    requisitos_tecnicos: 'Windows/Mac, GPU recomendada',
    categorias: {
      id: 'c4',
      nombre: 'Creatividad',
      _count: { productos: '3', usuarios: '0', productos_ofertas: '2' },
      productos: [],
    },
    plan: {
      id: 'pl4',
      nombre: 'Plan Creativo',
      costo: 14.99,
      beneficios: 'Filtros ilimitados y almacenamiento en la nube',
      _count: { suscripciones: 150, productos: 3 },
      suscripciones: [],
      productos: [],
      gananciasMensuales: 2249,
    },
    versiones: [
      {
        id: 'v5',
        producto_id: 'p5',
        numero_version: '2.0.0',
        urlarchivo: 'https://example.com/photo-v2.zip',
        fecha_lanzamiento: new Date('2024-03-15'),
        descripcion_cambios: 'Filtros basados en IA',
        size: '500MB',
        productos: {} as Productos,
      },
    ],
    registro_productos: [],
    productos_ofertas: [],
  },
  {
    id: 'p6',
    id_categoria: 4,
    oferta: false,
    compra: false,
    like: true,
    _count: { likes: 400, ventas: 150 },
    likeCount: 400,
    nombre: 'PhotoMaster Studio',
    descripcion:
      'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.',
    precio: 0,
    precio_actual: { precio: 0, descuento: 0 },
    fecha_registro: new Date('2024-02-10'),
    requisitos_tecnicos: 'Windows/Mac, GPU recomendada',
    categorias: {
      id: 'c4',
      nombre: 'Creatividad',
      _count: { productos: '3', usuarios: '0', productos_ofertas: '2' },
      productos: [],
    },
    plan: {} as any,
    versiones: [
      {
        id: 'v5',
        producto_id: 'p5',
        numero_version: '2.0.0',
        urlarchivo: 'https://example.com/photo-v2.zip',
        fecha_lanzamiento: new Date('2024-03-15'),
        descripcion_cambios: 'Filtros basados en IA',
        size: '500MB',
        productos: {} as Productos,
      },
    ],
    registro_productos: [],
    productos_ofertas: [],
  },
  {
    id: 'p7',
    id_categoria: 4,
    oferta: false,
    compra: false,
    like: true,
    _count: { likes: 400, ventas: 150 },
    likeCount: 400,
    nombre: 'App Creativa Lite',
    descripcion: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.',
    precio: 0,
    precio_actual: { precio: 0, descuento: 0 },
    fecha_registro: new Date('2024-02-10'),
    requisitos_tecnicos: 'Windows/Mac, GPU recomendada',
    categorias: {
      id: 'c4',
      nombre: 'Creatividad',
      _count: { productos: '3', usuarios: '0', productos_ofertas: '2' },
      productos: [],
    },
    plan: {} as any,
    versiones: [
      {
        id: 'v5',
        producto_id: 'p5',
        numero_version: '2.0.0',
        urlarchivo: 'https://example.com/photo-v2.zip',
        fecha_lanzamiento: new Date('2024-03-15'),
        descripcion_cambios: 'Filtros basados en IA',
        size: '500MB',
        productos: {} as Productos,
      },
    ],
    registro_productos: [],
    productos_ofertas: [],
  },
];
